# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under requirements_classification/resources/*
# and requirements_classification/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for requirements_classification Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./requirements_classification

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: requirements_classification-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t mlops_prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t mlops_prod
